In [32]:
import pandas as pd
import numpy as np
import string
import re
# from gensim.parsing.preprocessing import preprocess_string


In [3]:
pip install wikipedia-api


In [4]:
pip install wikipedia-api requests


In [5]:
import wikipediaapi
import requests

def get_formatted_lines(page_title):
    # Set the user agent in the headers
    headers = {
        'User-Agent': 'YourApp/1.0 (https://yourapp.com)'
    }

    # Create a Wikipedia session with the specified headers
    wiki_wiki = wikipediaapi.Wikipedia('en', extract_format=wikipediaapi.ExtractFormat.WIKI, headers=headers)

    page = wiki_wiki.page(page_title)

    if not page.exists():
        print("Page not found.")
        return []

    formatted_lines = []

    for section in page.sections:
        for line in section.text.split('\n'):
            if line.strip():
                formatted_lines.append(line.strip())

    return formatted_lines

if __name__ == "__main__":
    page_title = "Python (programming language)"
    lines = get_formatted_lines(page_title)

    for line in lines:
        print(line)


Python was conceived in the late 1980s by Guido van Rossum at Centrum Wiskunde & Informatica (CWI) in the Netherlands as a successor to the ABC programming language, which was inspired by SETL, capable of exception handling and interfacing with the Amoeba operating system. Its implementation began in December 1989. Van Rossum shouldered sole responsibility for the project, as the lead developer, until 12 July 2018, when he announced his "permanent vacation" from his responsibilities as Python's "benevolent dictator for life", a title the Python community bestowed upon him to reflect his long-term commitment as the project's chief decision-maker. In January 2019, active Python core developers elected a five-member Steering Council to lead the project.Python 2.0 was released on 16 October 2000, with many major new features such as list comprehensions, cycle-detecting garbage collection, reference counting, and Unicode support. Python 3.0, released on 3 December 2008, with many of its maj

In [6]:
dataset=lines

In [7]:
def replace_special_characters(input_string):
    pattern = r'[^a-zA-Z0-9\s]'
    return re.sub(pattern, "", input_string).lower()

In [8]:
dataset_clean = [replace_special_characters(line) for line in dataset]

In [9]:
dataset_clean

['python was conceived in the late 1980s by guido van rossum at centrum wiskunde  informatica cwi in the netherlands as a successor to the abc programming language which was inspired by setl capable of exception handling and interfacing with the amoeba operating system its implementation began in december 1989 van rossum shouldered sole responsibility for the project as the lead developer until 12 july 2018 when he announced his permanent vacation from his responsibilities as pythons benevolent dictator for life a title the python community bestowed upon him to reflect his longterm commitment as the projects chief decisionmaker in january 2019 active python core developers elected a fivemember steering council to lead the projectpython 20 was released on 16 october 2000 with many major new features such as list comprehensions cycledetecting garbage collection reference counting and unicode support python 30 released on 3 december 2008 with many of its major features backported to pytho

In [10]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [11]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(dataset_clean)

In [12]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'python': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'in': 7,
 'is': 8,
 'as': 9,
 'for': 10,
 'language': 11,
 'be': 12,
 'with': 13,
 'programming': 14,
 'are': 15,
 'it': 16,
 'by': 17,
 'has': 18,
 'such': 19,
 'that': 20,
 'languages': 21,
 'used': 22,
 'was': 23,
 'its': 24,
 'code': 25,
 'also': 26,
 'many': 27,
 'than': 28,
 'which': 29,
 'security': 30,
 'or': 31,
 'syntax': 32,
 'standard': 33,
 'like': 34,
 'from': 35,
 'on': 36,
 'releases': 37,
 'other': 38,
 'including': 39,
 'version': 40,
 'use': 41,
 'since': 42,
 'development': 43,
 'uses': 44,
 'can': 45,
 'pythons': 46,
 'will': 47,
 '2022': 48,
 'new': 49,
 'features': 50,
 'support': 51,
 'include': 52,
 'issues': 53,
 'were': 54,
 'eg': 55,
 '312': 56,
 'some': 57,
 'modules': 58,
 'design': 59,
 'library': 60,
 'applications': 61,
 'more': 62,
 'c': 63,
 'scripting': 64,
 'at': 65,
 'released': 66,
 'major': 67,
 'reference': 68,
 'only': 69,
 'supported': 70,
 'program': 71,
 'most': 72,
 'part': 7

In [13]:
tokenizer.texts_to_sequences([dataset_clean[0]])[0]

[3,
 23,
 360,
 7,
 2,
 175,
 361,
 17,
 129,
 77,
 102,
 65,
 362,
 363,
 364,
 365,
 7,
 2,
 366,
 9,
 5,
 367,
 4,
 2,
 176,
 14,
 11,
 29,
 23,
 368,
 17,
 369,
 370,
 6,
 177,
 178,
 1,
 371,
 13,
 2,
 372,
 179,
 130,
 24,
 78,
 373,
 7,
 103,
 374,
 77,
 102,
 375,
 376,
 377,
 10,
 2,
 180,
 9,
 2,
 181,
 378,
 182,
 379,
 380,
 183,
 131,
 381,
 184,
 104,
 382,
 383,
 35,
 104,
 384,
 9,
 46,
 385,
 386,
 10,
 387,
 5,
 388,
 2,
 3,
 79,
 389,
 390,
 391,
 4,
 392,
 104,
 393,
 394,
 9,
 2,
 132,
 395,
 396,
 7,
 185,
 397,
 186,
 3,
 80,
 81,
 398,
 5,
 399,
 187,
 400,
 4,
 181,
 2,
 401,
 133,
 23,
 66,
 36,
 402,
 188,
 403,
 13,
 27,
 67,
 49,
 50,
 19,
 9,
 105,
 189,
 190,
 191,
 404,
 68,
 192,
 1,
 405,
 51,
 3,
 193,
 66,
 36,
 82,
 103,
 106,
 13,
 27,
 6,
 24,
 67,
 50,
 406,
 4,
 3,
 407,
 1,
 408,
 37,
 6,
 3,
 82,
 52,
 2,
 409,
 410,
 29,
 411,
 2,
 412,
 6,
 3,
 413,
 25,
 4,
 3,
 414,
 415,
 194,
 23,
 416,
 195,
 10,
 417,
 418,
 419,
 4,
 134,
 420,
 6,
 4

In [14]:
## Creating input sequences (X, y)
input_sequences = []
for line in dataset_clean:
    token_list =tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

In [15]:
input_sequences

[[3, 23],
 [3, 23, 360],
 [3, 23, 360, 7],
 [3, 23, 360, 7, 2],
 [3, 23, 360, 7, 2, 175],
 [3, 23, 360, 7, 2, 175, 361],
 [3, 23, 360, 7, 2, 175, 361, 17],
 [3, 23, 360, 7, 2, 175, 361, 17, 129],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362, 363],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362, 363, 364],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362, 363, 364, 365],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362, 363, 364, 365, 7],
 [3, 23, 360, 7, 2, 175, 361, 17, 129, 77, 102, 65, 362, 363, 364, 365, 7, 2],
 [3,
  23,
  360,
  7,
  2,
  175,
  361,
  17,
  129,
  77,
  102,
  65,
  362,
  363,
  364,
  365,
  7,
  2,
  366],
 [3,
  23,
  360,
  7,
  2,
  175,
  361,
  17,
  129,
  77,
  102,
  65,
  362,
  363,
  364,
  365,
  7,
  2,
  366,
  

In [16]:
max_seq_len = max(len(x) for x in input_sequences)
print(max_seq_len)

237


In [17]:
input_sequences_padded = pad_sequences(input_sequences, maxlen=max_seq_len)

In [18]:
input_sequences_padded

array([[   0,    0,    0, ...,    0,    3,   23],
       [   0,    0,    0, ...,    3,   23,  360],
       [   0,    0,    0, ...,   23,  360,    7],
       ...,
       [   0,    0,    0, ...,  357,  358,  128],
       [   0,    0,    0, ...,  358,  128, 1160],
       [   0,    0,    0, ...,    0,  168, 1161]], dtype=int32)

In [19]:
X = input_sequences_padded[:, :-1] # Predictor
y = input_sequences_padded[:, -1]  # Target

In [20]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3], dtype=int32)

In [21]:
y[0]

23

In [22]:
len(y)

2945

In [23]:
y

array([  23,  360,    7, ...,  128, 1160, 1161], dtype=int32)

In [24]:
y_ohe =  to_categorical(y)

In [25]:
print(X.shape)
print(y_ohe.shape)

(2945, 236)
(2945, 1162)


In [26]:
len(tokenizer.word_index.keys())

1161

### LSTM Model

In [48]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Embedding, Dense

In [45]:
model = Sequential()
model.add(Embedding(1162,10,input_length=236))
model.add(LSTM(50))
model.add(Dense(1162, activation="softmax"))

In [49]:
adam_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

In [50]:
model.compile(optimizer=adam_optimizer, loss="categorical_crossentropy")

In [51]:
model.fit(X, y_ohe,epochs=10, validation_split=0.3)

Epoch 1/10
65/65 [==============================] - 12s 149ms/step - loss: 5.9661 - val_loss: 6.7250
Epoch 2/10
65/65 [==============================] - 8s 121ms/step - loss: 5.8689 - val_loss: 6.9745
Epoch 3/10
65/65 [==============================] - 9s 139ms/step - loss: 5.8207 - val_loss: 7.1118
Epoch 4/10
65/65 [==============================] - 9s 139ms/step - loss: 5.7706 - val_loss: 7.2545
Epoch 5/10
65/65 [==============================] - 8s 121ms/step - loss: 5.7119 - val_loss: 7.4312
Epoch 6/10
65/65 [==============================] - 9s 139ms/step - loss: 5.6453 - val_loss: 7.5050
Epoch 7/10
65/65 [==============================] - 9s 146ms/step - loss: 5.5679 - val_loss: 7.6659
Epoch 8/10
65/65 [==============================] - 9s 133ms/step - loss: 5.4940 - val_loss: 7.7830
Epoch 9/10
65/65 [==============================] - 9s 144ms/step - loss: 5.4232 - val_loss: 7.8458
Epoch 10/10
65/65 [==============================] - 9s 146ms/step - loss: 5.3481 - val_loss: 7.880

### Generating Output

In [52]:
# start_text = ["new york"]
start_text = ["list of"]

input_sequences_for_pred = []
for line in start_text:
    token_list =tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences_for_pred.append(n_gram_seq)

X_test = pad_sequences(input_sequences_for_pred, maxlen=236)
preds = model.predict(X_test)
pred_index = np.argmax(preds)

# index_word_dict = {v: k for k, v in tokenizer.word_index.items()}
tokenizer.index_word[pred_index]

1/1 [==============================] - 0s 435ms/step


'the'